defaults: &defaults
  enable_logging: true
  enable_rationale: true
  check_crosswalk: false
  nlm:
    ticket_url: https://vsac.nlm.nih.gov/vsac/ws/Ticket
    api_url: https://vsac.nlm.nih.gov/vsac/ws/RetrieveValueSet

development:
  <<: *defaults
  
test:
  <<: *defaults
  
production:
  <<: *defaults
