defaults: &defaults
  version: 2.0.5
  hqmfjs_libraries_version: 2.0.0
  enable_logging: true
  enable_rationale: true
  check_crosswalk: false
  measure_period_start: 1325376000
  nlm:
    ticket_url: https://vsac.nlm.nih.gov/vsac/ws/Ticket
    api_url: https://vsac.nlm.nih.gov/vsac/svs/RetrieveMultipleValueSets
    profiles_url: https://vsac.nlm.nih.gov/vsac/profiles
    profile: Latest eCQM
  enable_client_error_email: true
  # oldest version of QDM that can be loaded
  support_qdm_version: 5.3

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
