defaults: &defaults
  version: 1.5.3
  hqmfjs_libraries_version: 2.0.0
  enable_logging: true
  enable_rationale: true
  check_crosswalk: false
  measure_period_start: 1325376000
  nlm:
    ticket_url: https://vsac.nlm.nih.gov/vsac/ws/Ticket
    api_url: https://vsac.nlm.nih.gov/vsac/svs/RetrieveMultipleValueSets
    profiles_url: https://vsac.nlm.nih.gov/vsac/profiles
    profile: MU2 Update 2016-04-01
  record:
    # This value should not exceed 16000000 as that is the current size limit of a document in MongoDB.
    max_size_in_bytes: 12000000

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
