defaults: &defaults
  version: 5.1.1
  enable_logging: true
  enable_rationale: true
  check_crosswalk: false
  vsac:
    auth_url: https://vsac.nlm.nih.gov/vsac/ws
    content_url: https://vsac.nlm.nih.gov/vsac/svs
    utility_url: https://vsac.nlm.nih.gov/vsac
    default_profile: eCQM Update 2020-05-07
    default_program: CMS eCQM and Hybrid Measure
    default_release: eCQM Update 2020-05-07
  enable_client_error_email: true
  # oldest version of QDM that can be loaded
  support_qdm_version: 5.6
  # the harp instance that we use for authentication
  harp_idp_url: https://harp.cms.gov/login
  # Place holder email addresses for email alerts. This email is not valid.
  # This email should be configured in a '<root>/config/email.yml' file
  # for deployments.
  smtp_hostname: "localhost"
  smtp_port: 25
  smtp_tls: false
  bonnie_email: bonnie@example.com # For standard notifications
  bonnie_from_email: dont-reply-sb-bonnie-help@hcqis.org # For email sender
  bonnie_error_email: bonnie@example.com # For frontend/backend exceptions
  patient_conversion_service_url: https://bonniedev-fhir.semanticbits.com/bonnie-patient-conversion/patients/convertMany
  ## --- Session auto-logout ---
  # Show inactive session warning MS, default is 1500000 (25 min)
  show_warning_inactive_ms: 1500000
  # Logout inactive session MS, default is 1800000 (30 min)
  logout_inactive_ms: 1800000

  virus_scan:
    enabled: false
    scan_url: 'http://localhost:5000/scan-file'
    api_key: '1234567'
    timeout: 30

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
  patient_conversion_service_url: <%= ENV["BONNIE_PATIENT_CONV_URL"] %>
  hostname: <%= ENV["BONNIE_HOSTNAME"] %>
  smtp_hostname: <%= ENV["BONNIE_SMTP_HOSTNAME"] %>
  smtp_port: <%= ENV["BONNIE_SMTP_PORT"] %>
  smtp_username: <%= ENV["BONNIE_SMTP_USERNAME"] %>
  smtp_password: <%= ENV["BONNIE_SMTP_PASSWORD"] %>
  smtp_tls: <%= ENV["BONNIE_SMTP_TLS"] %>
  bonnie_email: <%= ENV["BONNIE_EMAIL"] %>
  bonnie_error_email: <%= ENV["BONNIE_ERROR_EMAIL"] %>
  bonnie_from_email: <%= ENV["BONNIE_FROM_EMAIL"] %>
  virus_scan:
    enabled: <%= ENV["VIRUS_SCAN_ENABLED"] %>
    scan_url: <%= ENV["VIRUS_SCAN_URL"] %>
    api_key: <%= ENV["VIRUS_SCAN_API_KEY"] %>
